"""Generate service/prompts/schema_<version>.md, the database description the planner prompt reads.

Tables, views, columns and types come from information_schema; the measure list and the
example values come from the data itself, so the description cannot drift from the
database. The short usage notes at the bottom are the only hand-written part; they record
quirks found in schema.sql, sql/views.sql and etl/clean.py.

The text-case profile and the per-relation coverage (which states each table or view spans)
are also measured from the data.

Run as the database owner:  python -m service.build_schema_context --version v2
(default v2; schema_v1.md is a frozen earlier version and is never regenerated by default)
"""
from __future__ import annotations

import argparse
import os
import re
from pathlib import Path

import psycopg
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
PROMPTS = ROOT / "service" / "prompts"
SCHEMA = "hq"

# (relation, column) pairs whose few distinct values are worth showing.
EXAMPLE_COLUMNS = [
    ("hospitals", "state"), ("hospitals", "hospital_type"), ("hospitals", "hospital_ownership"),
    ("hospitals", "emergency_services"), ("hospitals", "county"),
    ("measure_values", "value_type"), ("measure_values", "compared_to_national"),
    ("measures", "domain"), ("measures", "value_type"),
]

NOTES = """\
## Usage notes (data quirks)

- Always qualify names with the `hq.` schema (for example `hq.hospitals`).
- `hq.measure_values` is a long table: one row per (facility, measure, reporting period).
  `score` is NULL for about 40% of rows (CMS "Not Available", "Number of Cases Too Small"
  and similar become NULL, never 0). Filter `score IS NOT NULL` before averaging or ranking.
  Some measures (for example Hybrid_HWR) have no score for any hospital.
- Periods: `period_start` / `period_end` are the dates of the data window. A hospital can
  have several periods for one measure. For "current" values take the latest `period_end`
  per (facility_id, measure_id), or use `hq.v_tx_latest`, which already does.
- `hq.hospitals.is_texas` and `is_houston_area` are boolean flags. Houston-area means a
  Texas hospital in HARRIS, FORT BEND, MONTGOMERY, BRAZORIA or GALVESTON county.
  County names are stored UPPERCASE ("HARRIS"). State is a 2-letter code.
- Texas and Houston questions: prefer `hq.v_tx_latest` (Texas only, latest period, non-null
  scores, hospital columns included) or `hq.v_scorecard` (one row per Texas hospital with
  eleven key measures as columns). Use `hq.v_tx_latest` for a measure not in the scorecard.
  Hospitals with no score for a measure are absent from `v_tx_latest`; use
  `hq.hospitals` with a LEFT JOIN when they must be kept.
- National or all-state questions: use `hq.measure_values` joined to `hq.hospitals`, or
  `hq.v_benchmarks` (latest value per hospital for 11 key measures, all states, with
  `national_avg`, `state_avg` and `national_pct_rank`). `hq.v_tx_vs_national` has the
  Texas-versus-national summary for those 11 measures.
- Measure direction: `measures.higher_is_better` is false for readmission, mortality,
  infection (SIR) and ED-wait measures, true for care-process and patient-experience
  measures, and NULL where undecided. Low percentile / low rate is good only when
  `higher_is_better` is false.
- Measures are identified by `measure_id` (text, for example `READM_30_PN`); a measure_id
  maps to exactly one domain. Use the measure list above; never invent an id.
- `measure_values.measure_name` and `measures.measure_name` hold the long CMS description.
  HCAHPS rows with `value_type = 'answer_percent'` are survey answer percentages
  (`H_RECMND_DY` = would definitely recommend; `H_HSP_RATING_9_10` = rated 9 to 10).
- `hospitals.overall_rating` is the CMS overall star rating (1 to 5), NULL if unrated.
- `denominator` is the case or survey count behind a score (use it for weighted means).
"""


def _fetch(cur, q, params=()):
    cur.execute(q, params)
    return cur.fetchall()


def _case_profile(cur) -> list[str]:
    """How every text column of the base tables is cased, measured from the rows."""
    out = ["## Text case in the base tables (measured)",
           "Compare text case-insensitively (`UPPER(col) = 'X'` or `ILIKE`); never rely on a guessed case."]
    cols = _fetch(cur, "select c.table_name, c.column_name from information_schema.columns c "
                       "join information_schema.tables t using (table_schema, table_name) "
                       "where c.table_schema = %s and t.table_type = 'BASE TABLE' "
                       "and c.data_type in ('text', 'character varying', 'character') "
                       "order by 1, c.ordinal_position", (SCHEMA,))
    for rel, col in cols:
        q = f'"{col}"'
        n, up, low, mixed = _fetch(
            cur, f"select count(*) filter (where {q} ~ '[A-Za-z]'), "
                 f"count(*) filter (where {q} ~ '[A-Za-z]' and {q} = upper({q})), "
                 f"count(*) filter (where {q} ~ '[A-Za-z]' and {q} = lower({q})), "
                 f"count(*) filter (where {q} <> upper({q}) and {q} <> lower({q})) "
                 f"from {SCHEMA}.\"{rel}\"")[0]
        if n == 0:
            continue
        if up == n:
            desc = "all UPPERCASE"
        elif low == n:
            desc = "all lowercase"
        elif up / n >= 0.9:
            desc = f"mostly UPPERCASE ({up:,} of {n:,} values); {mixed:,} contain lowercase letters"
        elif mixed == n:
            desc = "Mixed / Title Case"
        else:
            desc = f"mixed: {up:,} uppercase, {low:,} lowercase, {mixed:,} mixed / Title Case (of {n:,})"
        out.append(f"- hq.{rel}.{col}: {desc}")
    out.append("")
    return out


def _coverage(cur, rels) -> list[str]:
    """Which states each relation's rows span (via facility_id -> hq.hospitals.state)."""
    out = ["## Coverage of every table and view (measured: states spanned)",
           "Pick the relation whose coverage matches the geography asked about."]
    for name, kind in rels:
        cols = {r[0] for r in _fetch(cur, "select column_name from information_schema.columns "
                                          "where table_schema = %s and table_name = %s", (SCHEMA, name))}
        label = f"hq.{name} ({'view' if kind == 'VIEW' else 'table'})"
        if "facility_id" not in cols:
            src = ""
            if kind == "VIEW":
                vd = _fetch(cur, f"select pg_get_viewdef('{SCHEMA}.{name}'::regclass)")[0][0]
                refs = sorted(set(re.findall(r"hq\.(\w+)", vd)) - {name})
                src = "; computed from " + ", ".join(f"hq.{r}" for r in refs) if refs else ""
            out.append(f"- {label}: no facility rows (summary or lookup rows){src}")
            continue
        states = [r[0] for r in _fetch(
            cur, f'select distinct h.state from {SCHEMA}."{name}" x join {SCHEMA}.hospitals h '
                 f'on h.facility_id = x.facility_id order by 1')]
        nfac = _fetch(cur, f'select count(distinct facility_id) from {SCHEMA}."{name}"')[0][0]
        if len(states) == 1:
            span = f"ONLY state {states[0]}"
        else:
            span = f"{len(states)} distinct state codes (national, including territories)"
        out.append(f"- {label}: {span}; {nfac:,} distinct facilities")
    out.append("")
    return out


def build() -> str:
    load_dotenv(ROOT / ".env")
    out = ["# Database schema: hospital quality (PostgreSQL, schema `hq`)", "",
           "Generated by service/build_schema_context.py from the live database. Do not edit by hand.", ""]
    with psycopg.connect(os.environ["DATABASE_URL"], connect_timeout=20) as conn:
        cur = conn.cursor()
        rels = _fetch(cur, "select table_name, table_type from information_schema.tables "
                           "where table_schema = %s order by table_type, table_name", (SCHEMA,))
        for name, kind in rels:
            n = _fetch(cur, f'select count(*) from {SCHEMA}."{name}"')[0][0]
            out.append(f"## hq.{name} ({'view' if kind == 'VIEW' else 'table'}, {n:,} rows)")
            for col, typ, nullable in _fetch(
                    cur, "select column_name, data_type, is_nullable from information_schema.columns "
                         "where table_schema = %s and table_name = %s order by ordinal_position", (SCHEMA, name)):
                out.append(f"- {col} {typ}{' NULL' if nullable == 'YES' else ''}")
            out.append("")

        out.append("## Example values for low-cardinality text columns")
        for rel, col in EXAMPLE_COLUMNS:
            vals = _fetch(cur, f'select "{col}", count(*) from {SCHEMA}."{rel}" where "{col}" is not null '
                               f'group by 1 order by 2 desc limit 3')
            ndist = _fetch(cur, f'select count(distinct "{col}") from {SCHEMA}."{rel}"')[0][0]
            shown = ", ".join(f"'{v}'" for v, _ in vals)
            out.append(f"- hq.{rel}.{col} ({ndist} distinct; most common): {shown}")
        out.append("")

        out += _case_profile(cur)
        out += _coverage(cur, rels)

        out.append("## Measures (hq.measures): measure_id | domain | value_type | direction | name")
        out.append("direction: higher = higher is better, lower = lower is better, ? = undecided")
        for mid, dom, vt, hib, nm in _fetch(
                cur, "select measure_id, domain, value_type, higher_is_better, measure_name "
                     "from hq.measures order by domain, measure_id"):
            d = "?" if hib is None else ("higher" if hib else "lower")
            out.append(f"- {mid} | {dom} | {vt} | {d} | {(nm or '').strip()[:90]}")
        out.append("")
    out.append(NOTES)
    return "\n".join(out)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--version", default="v2", help="writes service/prompts/schema_<version>.md (default v2)")
    OUT = PROMPTS / f"schema_{ap.parse_args().version}.md"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print("wrote", OUT, f"({OUT.stat().st_size:,} bytes)")
